import type { Project } from "./types";
export const demo: Project = {
 source:{owner:"POLAZU",repository:"Design playground",ref:"local",url:""},framework:"HTML",skippedFileCount:0,
 files:{
 "/index.html":`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>Forma Studio</title><style>
 *{box-sizing:border-box}body{margin:0;font:15px/1.6 Arial,sans-serif;background:#fbfaf8;color:#222126}nav{display:flex;justify-content:space-between;padding:24px 40px;border-bottom:1px solid #e7e4df}a{color:inherit;text-decoration:none}main{padding:72px 56px}small{color:#79736c;letter-spacing:3px}h1{font-size:64px;line-height:1.08;letter-spacing:-3px;max-width:620px;margin:24px 0}p{color:#79736c;max-width:470px}button,.cta{border:0;background:#222126;color:white;padding:14px 24px;border-radius:28px;display:inline-block;margin:16px 8px 0 0;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:50px}.card{padding:28px;border-radius:18px;background:#e6e4f1;min-height:150px}.card:nth-child(2){background:#e8ecd9}.card:nth-child(3){background:#f5e2d6}h3{font-size:23px;margin:10px 0}#result{font-size:13px}
 </style></head><body><nav><strong>forma®</strong><a href="/about.html">Our story ↗</a></nav><main><small>MADE FOR YOUR NEXT IDEA</small><h1>Good design.<br>Great possibilities.</h1><p>A little space to explore your next big idea. Make it yours, one detail at a time.</p><a class="cta" href="/about.html">Explore the studio ↗</a><button id="sample" onclick="fetch('/api/example').then(r=>r.json()).then(x=>document.getElementById('result').textContent=JSON.stringify(x))">Try sample API</button><p id="result"></p><div class="cards"><article class="card"><small>01 / CREATE</small><h3>Start with curiosity.</h3></article><article class="card"><small>02 / EXPLORE</small><h3>Make room for play.</h3></article><article class="card"><small>03 / CONNECT</small><h3>Bring ideas together.</h3></article></div></main></body></html>`,
 "/about.html":`<!doctype html><html><head><title>Our story</title></head><body style="font-family:Arial;padding:60px;background:#e6e4f1"><a href="/">← Back home</a><h1>Our story</h1><p>Design is a conversation.</p></body></html>`
 }
};
